### ISSUE TITLE
Small changes

### ISSUE THREAD

**Issue by mohsinalimat** [mspvirajpatel/SwiftyBase#1]
Your title - A Swift library for Create Project in iOS ( Base Project)
New title - A Swift library for Create Project in iOS (Base Project)

And AppPListManager file change to AppPlistManager

**Comment by mspvirajpatel** [comment]
Solved Issue.
@mohsinalimat Thanks For Your Feedback. In Future, any other issue then told me.

**Comment by mohsinalimat** [comment]
Thanks and Sure 👍
